---
title: "Grab GCTB parRes from Gen"
output: NULL
date: 10-26-2020
author: "Jinliang Yang"
---


```{r setup, include=TRUE}
#setwd("~/Documents/Github/pvpDiallel/")
knitr::opts_knit$set(root.dir=normalizePath('../../'))
```


### format phenotype for GCTB

/common/jyanglab/shared/Gen_Xu/282_GCTB

```{r, eval=FALSE}
get_gctb_parres <- function(path="largedata/bayesS"){
  # df: must contain "FID" (family id), "IID" (individual id)
  # cols: the idx of the phenotype columns
  
  files <- list.files(path, pattern="parRes", full.names = TRUE)
  message(sprintf("###>>> [%s] files detected!", length(files)))
  
  res <- data.frame()
  for(i in 1:length(files)){
    ### read in the file by skip the first two rows:
    pres <- read.table(files[i], skip = 2)
    pres$par <- row.names(pres)
    pres$file <- files[i]
    pres$trait <- gsub(".*/|.parRes", "", pres$file)
    res <- rbind(res, pres)
  }
  return(res)
}


### Microbiome traits
m1 <- get_gctb_parres(path="/common/jyanglab/shared/Gen_Xu/282_GCTB/microbe_from_Mike/HN")
###>>> [116] files detected!
m2 <- get_gctb_parres(path="/common/jyanglab/shared/Gen_Xu/282_GCTB/microbe_from_Mike/LN")
###>>> [113] files detected!

### Leaf Nutrient traits
l1 <- get_gctb_parres(path="/common/jyanglab/shared/Gen_Xu/282_GCTB/leaf_nutrient_traits_Field/HN")
###>>> [15] files detected!
l2 <- get_gctb_parres(path="/common/jyanglab/shared/Gen_Xu/282_GCTB/leaf_nutrient_traits_Field/LN")
###>>> [15] files detected!

### yield component traits
# R-CD ratio
# HN_LN-CD: difference between HN and LN
y1 <- get_gctb_parres(path="/common/jyanglab/shared/Gen_Xu/282_GCTB/Yield_traits_from_Semra/HN")
###>>> [4] files detected!
y2 <- get_gctb_parres(path="/common/jyanglab/shared/Gen_Xu/282_GCTB/Yield_traits_from_Semra/LN")
###>>> [4] files detected!

out <- rbind(m1, m2, l1, l2, y1, y2)
write.table(out, "cache/gtcb_HN_LN_1869traits.csv", sep=",", row.names=FALSE, quote=FALSE)

```


### Plot the S results

```{r}
library(ggplot2)
df <- read.csv("cache/gtcb_HN_LN_1869traits.csv")
df$file <- gsub(".*282_GCTB\\/", "", df$file)
df$type <- gsub("\\/.*", "", df$file)
df$treatment <- gsub("N\\/.*", "N", df$file)
df$treatment <- gsub(".*\\/", "", df$treatment)
df$trait <- gsub(".*-", "", df$trait)


s <- subset(df, par %in% "S")
s$sd1 <- with(s, Mean-SD)
s$sd2 <- with(s, Mean+SD)

s <- subset(s, (sd1 >0 & sd2 >0) | (sd1 <0 &sd2 <0))
```

```{r}

S_sd_plot_stdN <- ggplot(s, aes(x=reorder(trait, Mean), y=Mean, color=type)) +
  geom_point() +
  geom_errorbar(aes(ymin=Mean-SD, ymax=Mean+SD), colour="black") +
  coord_flip() +
  scale_color_manual(values = c("leaf_nutrient_traits_Field"="#C00001", "microbe_from_Mike"="#008000", "Yield_traits_from_Semra"="darkblue")) +
  facet_wrap(~treatment, ncol = 2) +
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  theme_bw() +
  theme(axis.title.y = element_blank(),
        axis.text=element_text(size=16, face="bold"),
        strip.text.x = element_text(size = 16, face = "bold")
        )#+
  #theme(text = element_text(size=10))

S_sd_plot_stdN
```

# Non Zero SNPs

```{r}
nz <- subset(df, par %in% "NnzSnp")

p1 <- ggplot(nz, aes(x=type, y=log10(Mean), fill=type)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter() +
  scale_color_manual(values = c("leaf_nutrient_traits_Field"="#C00001", "microbe_from_Mike"="#008000", "Yield_traits_from_Semra"="darkblue")) +
  facet_wrap(~treatment, ncol = 2) +
  #geom_hline(yintercept=0, linetype="dashed", color = "red") +
  theme_bw() +
  theme(axis.title.y = element_blank(),
        axis.text=element_text(size=16, face="bold"),
        strip.text.x = element_text(size = 16, face = "bold")
        )#+
p1
```


# Non Zero SNPs

```{r}
h <- subset(df, par %in% "hsq")

p2 <- ggplot(h, aes(x=type, y=Mean, fill=type)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter() +
  scale_color_manual(values = c("leaf_nutrient_traits_Field"="#C00001", "microbe_from_Mike"="#008000", "Yield_traits_from_Semra"="darkblue")) +
  facet_wrap(~treatment, ncol = 2) +
  #geom_hline(yintercept=0, linetype="dashed", color = "red") +
  theme_bw() +
  theme(axis.title.y = element_blank(),
        axis.text=element_text(size=16, face="bold"),
        strip.text.x = element_text(size = 16, face = "bold")
        )#+
p2
```




```{r}
library(ggplot2)
df <- read.csv("cache/gtcb_LN_n150.csv")

s <- subset(df, par %in% "S")
s <- s[order(s$Mean, decreasing=FALSE),]

s$trait <- factor(s$trait, levels = s$trait)

s2 <- s
p <- ggplot(s2, aes(x=Mean, y=trait)) +
    geom_point() +
    xlab("S") +
    ylab("") +
    ggtitle("") +
    theme_classic() +
    labs(color = "") +
    #scale_y_continuous(limits = c(-1, 3)) +
    #geom_vline(xintercept=0, linetype="dashed", color = "red") +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=18, face="bold"),
          #axis.text.x = element_text(angle = 20, hjust=0.6),
          legend.position = c(0.8, 0.95), 
          #axis.text.x = element_text(angle = 20, hjust=0.6),
          legend.title = element_text(size=18, face="bold"),
          legend.text = element_text(size=18))
p + geom_vline(xintercept = 0)

```

## MCMC tracing plot

/work/jyanglab/mmeier/HAVELOCK_BG/data/group_data.rda

```{r}

ob <- read.csv("data/microbe_references.csv", header=T)

s1 <- merge(s1, ob, by.x="trait",  by.y="ASV")
s1 <- s1[order(s1$Mean),]


s2 <- merge(s2, ob, by.x="trait",  by.y="ASV")
s2 <- s2[order(s2$Mean),]

s2$sval <- s2$Mean+s2$SD
out2 <- subset(s2, sval < 0)

write.table(s1, "cache/microbe_HN.csv", sep=",", row.names=FALSE, quote=FALSE)
write.table(s2, "cache/microbe_LN.csv", sep=",", row.names=FALSE, quote=FALSE)
```

