---
title: "Get the GTCB Pars"
output: NULL
date: 04-26-2021
author: "Jinliang Yang"
---


```{r setup, include=TRUE}
#setwd("~/Documents/Github/pvpDiallel/")
knitr::opts_knit$set(root.dir=normalizePath('../../'))
```

## GTCB results from Gen

`/common/jyanglab/gxu6/project/2-Coopration/Mike_micro/GCTB_micro`

### HN Par results
```{r}
library(data.table)

f=list.files(path="/common/jyanglab/gxu6/project/2-Coopration/Mike_micro/GCTB_micro/HN/Results_HN", patt="parRes", full.names = TRUE)

df <- data.frame()
for(i in f){
  #t=gsub(".parRes","",i)
  d=fread(i,head=F,data.table=F)
  d$file <- i
  df <- rbind(df,d)
}

names(df)[1:3] <- c("Type", "value", "sd")
write.table(df,"cache/HN_parRes.csv", sep=",", col.names = T, quote=F, row.names = F)
```

### LN Par results
```{r}
f=list.files(path="/common/jyanglab/gxu6/project/2-Coopration/Mike_micro/GCTB_micro/LN/Results_LN", patt="parRes", full.names = TRUE)

df <- data.frame()
for(i in f){
  #t=gsub(".parRes","",i)
  d=fread(i,head=F,data.table=F)
  d$file <- i
  df <- rbind(df,d)
}

names(df)[1:3] <- c("Type", "value", "sd")
write.table(df,"cache/LN_parRes.csv", sep=",", col.names = T, quote=F, row.names = F)
```


















```{r}
HS <- read.table("data/GCTB_analysis/HN-Micro_pi_S_h.txt")
LS <- read.table("data/GCTB_analysis/LN-Micro_pi_S_h.txt")


HS 

HS$news <- HS$S+HS$sd_S
out1 <- subset(HS, news < 0)
out1$treatment <- "HN"

LS$news <- LS$S+LS$sd_S
out2 <- subset(LS, news < 0)
out2$treatment <- "LN"

out <- rbind(out1, out2)
write.table(out, "largedata/beneficial_microbes.csv", sep=",", row.names = FALSE, quote=FALSE)

```






############## below copied from Mike ############3
```{r}
library("tidyverse")

### add GCTB data to group data
lowN <- read_tsv("data/GCTB_analysis/LN-Micro_pi_S_h.txt")
colnames(lowN) <- c("ASV","lowN_Pi","lowN_sd_pi","lowN_S","lowN_sd_S","lowN_hsq","lowN_sd_hsq")

stdN <- read_tsv("data/GCTB_analysis/HN-Micro_pi_S_h.txt")
colnames(stdN) <- c("ASV","stdN_Pi","stdN_sd_pi","stdN_S","stdN_sd_S","stdN_hsq","stdN_sd_hsq")


group_data <- group_data %>%
  left_join(lowN) %>%
  left_join(stdN)

save(group_data, file = "data/group_data.rda")

load("data/group_data.rda")
library("ggrepel")

#### plot S score +N vs -N, overlay labels for groups with strong GWAS signal ####

microbe_traits <- read_csv("data/microbial_traits.csv")


top_traits <- microbe_traits %>%
  filter(GWAS_signal == "strong") %>%
  select(tax_group, N_treatment) %>%
  rename(GWAS_signal_N = N_treatment) %>%
  left_join(group_data)


group_data <- left_join(group_data, top_traits[, c("tax_group", "GWAS_signal_N")])
group_data$GWAS_signal_N <- ifelse(is.na(group_data$GWAS_signal_N), "none", group_data$GWAS_signal_N)
group_data$GWAS_signal_N <- factor(group_data$GWAS_signal_N, levels=c("stdN", "lowN", "none" ))


S_plot <- ggplot(group_data, aes(x=lowN_S, y=stdN_S, color=GWAS_signal_N)) +
  #h2_plot <- ggplot(group_data, aes(x=H2_lowN, y=H2_stdN, color=GWAS_signal_N)) +
  geom_point(size = 2) +
  geom_text_repel(data = . %>%
                    mutate(label = ifelse(tax_group %in% top_traits$tax_group,
                                          tax_group, "")),
                  aes(label = label),
                  #box.padding = 2,
                  #size = 2,
                  min.segment.length = 0,
                  max.overlaps = 150,
                  segment.color = 'grey50') +
  scale_color_manual(values = c("lowN"="#C00001", "stdN"="#008000", "none"="#cccccc")) +
  theme_classic() +
  theme(text = element_text(size=20)) +
  labs(y = bquote('S under +N treatment') , x = bquote(' S under -N treatment'))



S_plot

```
```{r}


## plot S with std deviation


sdata <- group_data %>%
  select(tax_group, stdN_S, lowN_S) %>%
  pivot_longer(cols =  ends_with("N_S"), names_to = "nitrogen", values_to = "S" ) %>%
  mutate(nitrogen = ifelse(nitrogen == "stdN_S", "+N", "-N"))


sdata_sd <- group_data %>%
  select(tax_group, stdN_sd_S, lowN_sd_S) %>%
  pivot_longer(cols =  ends_with("sd_S"), names_to = "nitrogen", values_to = "sd" ) %>%
  mutate(nitrogen = ifelse(nitrogen == "stdN_sd_S", "+N", "-N"))



S_data <- sdata %>%
  left_join(sdata_sd) %>%
  left_join(group_data)



S_sd_plot_stdN <- ggplot(S_data %>% filter(nitrogen == "+N") %>% drop_na(S) %>% filter(S > 0.5 | S < -0.5), aes(x=reorder(tax_group, S), y=S, color=GWAS_signal_N)) +
  geom_point() +
  geom_errorbar(aes(ymin=S-sd, ymax=S+sd), colour="black") +
  coord_flip() +
  scale_color_manual(values = c("lowN"="#C00001", "stdN"="#008000", "none"="#cccccc")) +
  facet_wrap(~nitrogen, ncol = 2) +
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  theme_bw() +
  theme(axis.title.y = element_blank(),
        axis.text=element_text(size=16, face="bold"),
        strip.text.x = element_text(size = 16, face = "bold")
        )#+
  #theme(text = element_text(size=10))

S_sd_plot_stdN

```



## H2 vs h2


```{r}
lowN_H2_h2 <- ggplot(group_data, aes(x=H2_lowN_19, y=lowN_hsq, color=GWAS_signal_N)) +
  geom_point(size = 2) +
  geom_text_repel(data = . %>%
                    mutate(label = ifelse(tax_group %in% top_traits$tax_group,
                                          tax_group, "")),
                  aes(label = label),
                  #box.padding = 2,
                  #size = 2,
                  min.segment.length = 0,
                  max.overlaps = 150,
                  segment.color = 'grey50') +
  scale_color_manual(values = c("lowN"="#C00001", "stdN"="#008000", "none"="#cccccc")) +
  theme_classic() +
  theme(text = element_text(size=20)) +
  labs(y = bquote('snp based heritability') , x = bquote('pedigree based heritability'))



lowN_H2_h2






stdN_H2_h2 <- ggplot(group_data, aes(x=H2_stdN_19, y=stdN_hsq, color=GWAS_signal_N)) +
  geom_point(size = 2) +
  geom_text_repel(data = . %>%
                    mutate(label = ifelse(tax_group %in% top_traits$tax_group,
                                          tax_group, "")),
                  aes(label = label),
                  #box.padding = 2,
                  #size = 2,
                  min.segment.length = 0,
                  max.overlaps = 150,
                  segment.color = 'grey50') +
  scale_color_manual(values = c("lowN"="#C00001", "stdN"="#008000", "none"="#cccccc")) +
  theme_classic() +
  theme(text = element_text(size=20)) +
  labs(y = bquote('snp based heritability') , x = bquote('pedigree based heritability'))



stdN_H2_h2





Pi_plot <- ggplot(group_data, aes(x=lowN_Pi, y=stdN_Pi, color=GWAS_signal_N)) +
  #h2_plot <- ggplot(group_data, aes(x=H2_lowN, y=H2_stdN, color=GWAS_signal_N)) +
  geom_point(size = 2) +
  geom_text_repel(data = . %>%
                    mutate(label = ifelse(tax_group %in% top_traits$tax_group,
                                          tax_group, "")),
                  aes(label = label),
                  #box.padding = 2,
                  #size = 2,
                  min.segment.length = 0,
                  max.overlaps = 150,
                  segment.color = 'grey50') +
  scale_color_manual(values = c("lowN"="#C00001", "stdN"="#008000", "none"="#cccccc")) +
  theme_classic() +
  theme(text = element_text(size=20),
        axis.text=element_text(size=20, face="bold")) +
  labs(y = bquote('polygenicity under +N treatment') , x = bquote('polygenicity under -N treatment'))



Pi_plot




```
```{r}
S_sd_plot_lowN <- ggplot(S_data %>% filter(nitrogen == "-N") %>% drop_na(S) %>% filter(S > 0.5 | S < -0.5), aes(x=reorder(tax_group, S), y=S, color=GWAS_signal_N)) +
  geom_point() +
  geom_errorbar(aes(ymin=S-sd, ymax=S+sd), colour="black") +
  coord_flip() +
  scale_color_manual(values = c("lowN"="#C00001", "stdN"="#008000", "none"="#cccccc")) +
  facet_wrap(~nitrogen, ncol = 2) +
  theme_bw() +
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  theme(axis.title.y = element_blank(),
        axis.text=element_text(size=16, face="bold"),
        strip.text.x = element_text(size = 16, face = "bold")
        )#+
#theme(text = element_text(size=10))

S_sd_plot_lowN

```

